# Generated by Django 4.0.1 on 2022-02-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateBillModel',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('bid', models.CharField(max_length=50, null=True)),
                ('uscno', models.IntegerField(max_length=50, null=True)),
                ('units', models.CharField(max_length=50, null=True)),
                ('bill', models.CharField(max_length=50, null=True)),
                ('date_of_bill', models.DateField(auto_now_add=True, null=True)),
                ('bill_status', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'db_table': 'Bill_details',
            },
        ),
    ]
