# Generated by Django 4.0.1 on 2022-02-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBillerModel',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('postalcode', models.IntegerField()),
            ],
            options={
                'db_table': 'AddBiller-Model',
            },
        ),
    ]
