# Generated by Django 4.0.1 on 2022-02-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewconnectionModel',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('usc', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Newconnection-Model',
            },
        ),
        migrations.CreateModel(
            name='RaisecomplaintsModel',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('complaint', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'raisecomplaints-Model',
            },
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Registration-Model',
            },
        ),
        migrations.CreateModel(
            name='ServicefeedbackModel',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('textarea', models.CharField(max_length=50)),
                ('date', models.DateTimeField(max_length=50)),
            ],
            options={
                'db_table': 'Servicefeedback-Model',
            },
        ),
    ]
