# Generated by Django 4.0.1 on 2022-02-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newconnectionmodel',
            name='usc',
        ),
        migrations.AddField(
            model_name='newconnectionmodel',
            name='apic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='newconnectionmodel',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newconnectionmodel',
            name='ipic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='newconnectionmodel',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newconnectionmodel',
            name='postalcode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newconnectionmodel',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='raisecomplaintsmodel',
            name='usc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicefeedbackmodel',
            name='usc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newconnectionmodel',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newconnectionmodel',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newconnectionmodel',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newconnectionmodel',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='raisecomplaintsmodel',
            name='complaint',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raisecomplaintsmodel',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raisecomplaintsmodel',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raisecomplaintsmodel',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicefeedbackmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeedbackmodel',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeedbackmodel',
            name='textarea',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
