# Generated by Django 4.0.1 on 2022-02-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_registrationmodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newconnectionmodel',
            name='mobile',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='raisecomplaintsmodel',
            name='mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
