# Generated by Django 4.0.1 on 2022-02-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_newconnectionmodel_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newconnectionmodel',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='raisecomplaintsmodel',
            name='select',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
