# Generated by Django 4.0.1 on 2022-02-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_newconnectionmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newconnectionmodel',
            name='uscno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
